name: dracula metrics server CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        go: [ '1.16', '1.17' ]
    name: Go v${{ matrix.go }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v ./...
      - run: go vet ./...
      - run: go build -o dracula cmd/main.go
